@echo off
setlocal enabledelayedexpansion

:: =============================================================================
:: BSEE - Simple & Robust Windows Launcher
:: =============================================================================
title BSEE - Binary Structure Exploration Engine
color 0A

:: Configuration
set PROJECT_DIR=%~dp0..
set VENV_DIR=%PROJECT_DIR%\venv
set LOG_FILE=%PROJECT_DIR%\logs\bsee_setup.log

:: Basic functions
:info
echo [INFO] %~1
goto :eof

:error
echo [ERROR] %~1
pause
goto :eof

:success
echo [SUCCESS] %~1
goto :eof

:: =============================================================================
:: MAIN EXECUTION
:: =============================================================================
call :info "Starting BSEE setup..."

:: Create logs directory
if not exist "%PROJECT_DIR%\logs" mkdir "%PROJECT_DIR%\logs%"

:: =============================================================================
:: STEP 1: Python Detection
:: =============================================================================
call :info "Step 1/5 - Checking Python installation..."

python --version >nul 2>&1
if errorlevel 1 (
    echo.
    echo [ERROR] Python is not installed or not in PATH
    echo Please install Python 3.9+ from: https://www.python.org/downloads/
    echo Make sure to check "Add Python to PATH" during installation
    pause
    exit /b 1
)

:: Get Python version
for /f "tokens=2" %%i in ('python --version 2^>^&1') do set PYTHON_VERSION=%%i
call :success "Found Python %PYTHON_VERSION%"

:: =============================================================================
:: STEP 2: Virtual Environment
:: =============================================================================
call :info "Step 2/5 - Setting up virtual environment..."

:: Remove corrupted venv
if exist "%VENV_DIR%" (
    if not exist "%VENV_DIR%\Scripts\activate.bat" (
        call :info "Removing corrupted virtual environment..."
        rmdir /s /q "%VENV_DIR%"
    )
)

:: Create virtual environment if not exists
if not exist "%VENV_DIR%" (
    call :info "Creating virtual environment..."
    python -m venv "%VENV_DIR%"
    if errorlevel 1 (
        call :error "Failed to create virtual environment"
        exit /b 1
    )
    call :success "Virtual environment created"
)

:: Activate virtual environment
if exist "%VENV_DIR%\Scripts\activate.bat" (
    call "%VENV_DIR%\Scripts\activate.bat"
    if errorlevel 1 (
        call :error "Failed to activate virtual environment"
        exit /b 1
    )
    call :success "Virtual environment activated"
) else (
    call :error "Virtual environment activation script not found"
    exit /b 1
)

:: =============================================================================
:: STEP 3: Dependencies
:: =============================================================================
call :info "Step 3/5 - Installing dependencies..."

:: Upgrade pip
python -m pip install --upgrade pip >nul 2>&1

:: Check requirements directory
set REQUIREMENTS_DIR=%PROJECT_DIR%\requirements
if exist "%REQUIREMENTS_DIR%" (
    :: Install from requirements files
    for %%f in ("%REQUIREMENTS_DIR%\*.txt") do (
        call :info "Installing %%~nf..."
        python -m pip install -r "%%f" >nul 2>&1
        if errorlevel 1 (
            call :info "Warning: Some packages in %%~nf failed to install"
        ) else (
            call :success "%%~nf installed successfully"
        )
    )
) else (
    :: Install basic requirements
    call :info "Installing basic requirements..."
    python -m pip install numpy scipy matplotlib pyyaml click pandas >nul 2>&1
    if errorlevel 1 (
        call :info "Warning: Some basic packages failed to install"
    )
)

:: =============================================================================
:: STEP 4: Python Path Fixes
:: =============================================================================
call :info "Step 4/5 - Fixing Python import paths..."

:: Set PYTHONPATH for BSEE modules
set PYTHONPATH=%PROJECT_DIR%;%PROJECT_DIR%\legacy;%PYTHONPATH%

:: Create bsee module if missing
if not exist "%PROJECT_DIR%\bsee" (
    call :info "Creating BSEE module structure..."
    mkdir "%PROJECT_DIR%\bsee" >nul 2>&1
    echo # BSEE Package > "%PROJECT_DIR%\bsee\__init__.py" >nul 2>&1
    echo # Auto-generated by BSEE.bat >> "%PROJECT_DIR%\bsee\__init__.py" >nul 2>&1
)

call :success "Python paths configured"

:: =============================================================================
:: STEP 5: Windows Integration
:: =============================================================================
call :info "Step 5/5 - Windows integration..."

:: Check admin privileges
net session >nul 2>&1
if %errorlevel% == 0 (
    set IS_ADMIN=1
    call :info "Administrator privileges detected"
) else (
    set IS_ADMIN=0
    call :info "Running with standard user privileges"
)

:: File associations (admin only)
if %IS_ADMIN% == 1 (
    assoc .bin=BSEEFile >nul 2>&1
    ftype BSEEFile="\"%PROJECT_DIR%\BSEE.bat\" \"%%1\"" >nul 2>&1
    call :success "File associations created"
)

:: Environment variables
setx BSEE_HOME "%PROJECT_DIR%" >nul 2>&1
call :success "Environment variables configured"

:: =============================================================================
:: STEP 6: Validation
:: =============================================================================
call :info "Step 6/6 - Validating setup..."

:: Test basic imports
python -c "
import sys
sys.path.insert(0, '.')
try:
    import numpy
    import scipy
    import matplotlib
    import yaml
    print('Core modules OK')
except ImportError as e:
    print(f'Import error: {e}')
    sys.exit(1)
" >nul 2>&1

if errorlevel 1 (
    call :info "Some core modules failed to import - continuing anyway"
) else (
    call :success "All core modules validated"
)

:: Test BSEE modules
python -c "
import sys
sys.path.insert(0, '.')
sys.path.insert(0, './legacy')
try:
    import bsee
    print('BSEE modules OK')
except ImportError as e:
    print(f'BSEE import error: {e}')
    sys.exit(1)
" >nul 2>&1

if errorlevel 1 (
    call :info "BSEE modules not found - running in development mode"
) else (
    call :success "BSEE modules validated"
)

:: =============================================================================
:: STEP 7: Launch Options
:: =============================================================================
call :info "Setup complete - Ready to launch BSEE"
echo.
echo.
echo ========================================
echo    BSEE Setup Complete
echo ========================================
echo.
echo  Select launch mode:
echo.
echo    [1] GUI Mode
echo    [2] CLI Mode
echo    [3] Test Mode
echo    [4] Exit
echo.

choice /c 1234 /n /m "Select option (1-4): "

if errorlevel 4 goto exit_bsee
if errorlevel 3 goto test_mode
if errorlevel 2 goto cli_mode
if errorlevel 1 goto gui_mode
goto main

:gui_mode
call :info "Starting BSEE GUI..."
if exist "%PROJECT_DIR%\legacy\gui_main.py" (
    python "%PROJECT_DIR%\legacy\gui_main.py"
    if errorlevel 1 (
        call :error "GUI failed to start"
        goto main
    )
    call :success "GUI started successfully"
) else (
    call :error "GUI file not found: %PROJECT_DIR%\legacy\gui_main.py"
)
goto main

:cli_mode
call :info "Starting BSEE CLI..."
if exist "%PROJECT_DIR%\legacy\main.py" (
    python "%PROJECT_DIR%\legacy\main.py" %*
) else (
    call :error "CLI file not found: %PROJECT_DIR%\legacy\main.py"
)
goto main

:test_mode
call :info "Running BSEE test suite..."
if exist "%PROJECT_DIR%\tests\test_smoke.py" (
    python "%PROJECT_DIR%\tests\test_smoke.py"
) else (
    call :error "Test file not found: %PROJECT_DIR%\tests\test_smoke.py"
)
goto main

:exit_bsee
call :info "Thank you for using BSEE!"
pause
exit /b 0

:main
echo.
pause
exit /b 0